#################################################################################
#  ---------------------------------------------------------------------------  #
#  |      ___                      ____               _                _     |  #
#  |     / _ \  _ __  ___         / ___| ___   _ __  | |_  _ __  ___  | |    |  #
#  |    | | | || '__|/ _ \ _____ | |    / _ \ | '_ \ | __|| '__|/ _ \ | |    |  #
#  |    | |_| || |  |  __/|_____|| |___| (_) || | | || |_ | |  | (_) || |    |  #
#  |     \___/ |_|   \___|        \____|\___/ |_| |_| \__||_|   \___/ |_|    |  #
#  |                                                                         |  #
#  |                                                                         |  #
#  |         SOURCE CODE: https://github.com/DerFrZocker/Ore-Control         |  #
#  |     BUG REPORTS: https://github.com/DerFrZocker/Ore-Control/issues      |  #
#  |               Donation: https://www.paypal.me/DerFrZocker               |  #
#  |           Patreon: https://www.patreon.com/woollydevelopment            |  #
#  |                                                                         |  #
#  |                You can find a version with comments here                |  #
#  |         https://github.com/DerFrZocker/Ore-Control/wiki/Config          |  #
#  |                                                                         |  #
#  |                                                                         |  #
#  |                                  NOTE:                                  |  #
#  |                          PLEASE KEEP IN MIND,                           |  #
#  |           THAT THE PLUGIN ONLY AFFECTS NEWLY GENERATED CHUNKS           |  #
#  |                                                                         |  #
#  ---------------------------------------------------------------------------  #
#################################################################################.



# When ever or not the plugin should allow you to set potential unsafe values, which can cause a server crash.
# 'true' (Default) : the plugin won't let you set potential unsafe values
# 'false' : the plugin will allow you to set potential unsafe values
safe-mode: true

# The language of the message from this plugin
# Currently following languages are supported:
# 'english' (Default)
# 'german' / 'deutsch' (fully translated)
# 'chinese' / '中国' / '中國' (not fully translated) (Thanks to Pings for the translation)
# 'custom' (default english)
#
# You can also submit a new Language if you want.
# Simply translate the messages.yml in the Ore-Control folder and send it to me
language: english

# If the tab compilation should also be translated
# Example instead of normal english '/orecontrol set value iron vein_size world 10'
# to the chosen language (in this example german) '/orecontrol set value eisen adergröße world 10'
# 'true' (Default) : translate
# 'false' : don't translate
translate-tab-compilation: true

# If the plugin should ask for verification, if you copy or reset values via the gui
# 'true' (Default) : ask for verification
# 'false' : don't ask for verification
verify:
  copy-action: true
  reset-action: true