name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
authors: [${project.authors}]
main: de.derfrzocker.ore.control.OreControl
api-version: "1.13"
load: STARTUP
commands:
  orecontrol:
    permission: "ore.control"

permissions:
  ore.control:
    description: "Base permission"
    default: op
  ore.control.*:
    description: "Gives access to all Ore Control commands and functions"
    default: op
    children:
      ore.control: true
      ore.control.set.*: true
      ore.control.reload: true
      ore.control.gui: true
      ore.control.template.*: true
      ore.control.value.*: true
      ore.control.config.edit: true
  ore.control.set.*:
    description: "Gives access to the subcommand 'set'  and 'setbiome' and to set normal and biome values via gui"
    default: op
    children:
      ore.control: true
      ore.control.set: true
      ore.control.set.biome: true
  ore.control.set:
    description: "Gives access to the subcommand 'set' and to set normal values via gui"
    default: op
    children:
      ore.control: true
      ore.control.gui: true
  ore.control.set.biome:
    description: "Gives access to the subcommand 'setbiome' and to set biome values via gui"
    default: op
    children:
      ore.control: true
      ore.control.gui: true
  ore.control.reload:
    description: "Gives access to the subcommand 'reload'"
    default: op
    children:
      ore.control: true
  ore.control.gui:
    description: "Gives access to the gui"
    default: op
    children:
      ore.control: true
  ore.control.template:
    description: "Base template permission"
    default: op
    children:
      ore.control: true
  ore.control.template.*:
    description: "Gives access to the subcommand 'create' and to create and delete templates via the gui"
    default: op
    children:
      ore.control.template: true
      ore.control.template.create: true
      ore.control.template.delete: true
  ore.control.template.create:
    description: "Gives access to the subcommand 'create' and to create templates via the gui"
    default: op
    children:
      ore.control.template: true
      ore.control.gui: true
  ore.control.template.delete:
    description: "Gives access to delete templates via the gui"
    default: op
    children:
      ore.control.template: true
      ore.control.gui: true
  ore.control.value:
    description: "Base value permission"
    default: op
    children:
      ore.control: true
  ore.control.value.*:
    description: "Gives access to reset and copy values via the gui"
    default: op
    children:
      ore.control.value: true
      ore.control.value.reset: true
      ore.control.value.copy: true
  ore.control.value.reset:
    description: "Gives access to reset values via the gui"
    default: op
    children:
      ore.control.value: true
      ore.control.gui: true
  ore.control.value.copy:
    description: "Gives access to copy values via the gui"
    default: op
    children:
      ore.control.value: true
      ore.control.gui: true
  ore.control.config.edit:
    description: "Gives access to edit the config via the gui"
    default: op
    children:
      ore.control: true
      ore.control.gui: true