name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.authors}
main: de.derfrzocker.ore.control.OreControl
api-version: 1.13
load: STARTUP
commands:
  orecontrol:
    permission: "ore.control"
