name: "%%translation:[all_settings_screen.name]%"
default-icon:
  item-stack:
    ==: org.bukkit.inventory.ItemStack
    v: 2865
    type: COAL
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "&f%%translation:[settings.%setting%.name]%"
      lore:
        - "   "
        - "%value-settings%"
        - "   "
        - "&7>> &b%%translation:[all_settings_screen.default-icon.lore.left-click]% &7<<"