name: "%%translation:[config_info_screen.name]%"
whole-world:
  slot: 23
  item-stack:
    ==: org.bukkit.inventory.ItemStack
    v: 2865
    type: STONE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "&f%%translation:[config_info_screen.whole-world.name]%"
      lore:
        - "   "
        - "&7>> &b%%translation:[config_info_screen.whole-world.lore.left-click]% &7<<"
biome:
  slot: 21
  item-stack:
    ==: org.bukkit.inventory.ItemStack
    v: 2865
    type: GRASS_BLOCK
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "&f%%translation:[config_info_screen.biome.name]%"
      lore:
        - "   "
        - "&7>> &b%%translation:[config_info_screen.biome.lore.left-click]% &7<<"