name: "%%translation:[feature_settings_screen.name]%"
default-icon:
  item-stack:
    ==: org.bukkit.inventory.ItemStack
    v: 1519
    type: COAL
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "&f%%translation:[settings.%setting%.name]%"
      lore:
        - "   "
        - "&7>> &b%%translation:[feature_settings_screen.default-icon.lore.left-click]% &7<<"