name: "%%translation:[feature_settings_screen.name]%"
skip-slots: 2
default-icon:
  item-stack:
    ==: org.bukkit.inventory.ItemStack
    v: 2865
    type: COAL
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "&f%%translation:[settings.%setting%.name]%"
      lore:
        - "   "
        - "%value-settings%"
        - "   "
        - "&7>> &b%%translation:[feature_settings_screen.default-icon.lore.left-click]% &7<<"
feature-generator:
  slot: 10
  item-stack:
    ==: org.bukkit.inventory.ItemStack
    v: 2865
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "&f%%translation:[namespaces.%feature-generator-namespace%.name]%: %%translation:[feature-generators.%feature-generator-namespace%.%feature-generator-key%.name]%"
      lore:
        - "   "
        - "&7>> &b%%translation:[feature_settings_screen.feature-generator.lore.left-click]% &7<<"
placement-modifier-icon:
  feature:
    activation:
      slot: 4
      unknown:
        item-stack:
          ==: org.bukkit.inventory.ItemStack
          v: 2865
          type: CYAN_TERRACOTTA
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: "&f%%translation:[settings.activate.name]%"
            lore:
              - "   "
              - "&7>> &b%%translation:[feature_settings_screen.default-icon.lore.left-click]% &7<<"
      true:
        item-stack:
          ==: org.bukkit.inventory.ItemStack
          v: 2865
          type: LIME_TERRACOTTA
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: "&f%%translation:[settings.activate.name]%"
            lore:
              - "   "
              - "&7>> &b%%translation:[feature_settings_screen.default-icon.lore.left-click]% &7<<"
      false:
        item-stack:
          ==: org.bukkit.inventory.ItemStack
          v: 2865
          type: RED_TERRACOTTA
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: "&f%%translation:[settings.activate.name]%"
            lore:
              - "   "
              - "&7>> &b%%translation:[feature_settings_screen.default-icon.lore.left-click]% &7<<"