name: "Choose A Setting!"
default-icon:
  item-stack:
    ==: org.bukkit.inventory.ItemStack
    v: 1519
    type: COAL
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '§f%setting-name%'
      lore:
        - "   "
        - "§7>> §bClick to edit this setting! §7<<"